services:
  - type: web
    name: meal-mate-backend
    runtime: python
    buildCommand: |
      cd backend && pip install -r requirements.txt
    startCommand: |
      cd backend && gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///instance/mealmate.db
      - key: SECRET_KEY
        generateValue: true

  - type: static
    name: meal-mate-frontend
    buildCommand: |
      cd meal-mate-frontend && npm install && npm run build
    staticFilesPath: meal-mate-frontend/dist
