services:
  - type: web
    name: meal-mate-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd ../meal-mate-frontend && npm install && npm run build
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///instance/mealmate.db
      - key: SECRET_KEY
        generateValue: true
    staticSites:
      - name: meal-mate-frontend
        buildCommand: |
          npm install
          npm run build
        staticFilesPath: meal-mate-frontend/dist
